name: ci

run-name: ${{ github.actor }} triggered CI

on: [push]

permissions:
  contents: read
  
jobs:
  test-all:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up env
        run: |
          sudo apt-get update
          sudo apt-get install cmake
          
